title: ROS2 学习笔记
description: 记录ROS2学习过程的个人博客
author: XqsZX
email: xin.zhao@email.com
baseurl: ""
url: "https://xqszx.github.io"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

timezone: Asia/Shanghai
lang: zh-CN